[package]
org = "ballerinax"
name = "health.fhir.templates.r4.uscore501.encounter"
version = "1.0.4-snapshot"
distribution = "2201.5.0"
authors = ["Ballerina"]
keywords = ["Healthcare", "FHIR", "Encounter", "r4", "uscore"]
template = true
repository = "https://github.com/ballerina-platform/module-ballerinax-health.fhir.templates"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "1.0.3"

[[dependency]]
org = "ballerinax"
name = "health.base"
version = "1.0.2"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.uscore501"
version = "1.0.3"
